defaults:
  - module/model: 14M

data:
  batch_size: 12288 
  num_workers: 4
  dataset_path: datasets/data-100m.txt
  seed: 42

  dataset_config:
    reason_net_token_num: 20

module:
  lr: 1e-3

module_name: "normal"

trainer:

  lightning:
    precision: "bf16-mixed"
    max_epochs: 1
    log_every_n_steps: 1
    devices: 1
    val_check_interval: 0.1
    
  save_dir: "lightning_logs"
  checkpoint_path: null

wandb:
  enabled: true
  project_name: "reason_net"
  name: null
