defaults:
  - module/model: 14M

data:
  batch_size: 8192 
  num_workers: 4
  dataset_path: datasets/data-100m.txt
  seed: 42

module:
  lr: 1e-3

trainer:

  lightning:
    precision: "32-true"
    max_epochs: 1
    log_every_n_steps: 1
    devices: 1
    val_check_interval: 0.1
    
  save_dir: "lightning_logs"
  checkpoint_path: null
  
wandb:
  enabled: true
  project_name: "reason_net"
  name: null
