defaults:
  - module/model: 70M

data:
  min: 0
  max: 6
  batch_size: 1024
  size: 1_000_000
  seed: 42
  num_workers: 4

module:
  lr: 1e-2

trainer:

  lightning:
    precision: "bf16-mixed"
    max_epochs: 1
    log_every_n_steps: 1
    devices: 1
    val_check_interval: 0.1
  
  wandb:
    enabled: true
    project_name: "reason_net"
