defaults:
  - module/model: 70M

data:
  min: 0
  max: 3
  batch_size: 8
  size: 256
  seed: 42

module:
  lr: 1e-2

trainer:

  lightning:
    precision: "bf16-mixed"
    max_epochs: 10
    log_every_n_steps: 1
    devices: 1
  
  wandb:
    enabled: false
    project_name: "reason_net"
