defaults:
  - module/model: 14M

data:
  batch_size: 12288 
  num_workers: 4
  dataset_path: datasets/data-100m.txt

  reason_net_token_num: 20
  reason_net_data: false

module:
  lr: 1e-3

reason_mode: false

trainer:

  pl:
    devices: 1
    
  save_dir: "lightning_logs"

wandb:
  enabled: true
  project_name: "reason_net"
