defaults:
  - module/model: 14M

data:
  min: 0
  max: 6
  batch_size: 8192 
  size: 1_000_000
  seed: 42
  num_workers: 4

module:
  lr: 1e-2

trainer:

  lightning:
    precision: "32-true"
    max_epochs: 10
    log_every_n_steps: 1
    devices: 1
    val_check_interval: 0.1
    
  save_dir: "lightning_logs"
  
  wandb:
    enabled: true
    project_name: "reason_net"
