reason_mode: false

defaults:
  - module/model: single-layer
  - default
  - _self_

data:
  batch_size: 8196
  train_prop: 0.1
  num_workers: 4
  dataset_path: datasets/data-25m-add.txt

module:
  lr: 1e-2
  weight_decay: 1

trainer:
  pl:
    val_check_interval: 1

wandb:
  enabled: true
  project_name: "reason_net_add"
